name: sugi_lint
description: Custom lints rules used in Clean Architecture.
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  analyzer: ^6.4.1
  change_case: ^2.0.1
  custom_lint_builder: ^0.6.4
dev_dependencies:
  cli_util: ^0.4.1
  custom_lint: ^0.6.4
  lints: ^3.0.0
